### ISSUE TITLE
Week 1 prototypes

### ISSUE THREAD

**Issue by bloche14** [jdespland-teaching/CART315_2020#1]
Please share links to your games here

**Comment by Willler** [comment]
William L'Eriger

https://willler.github.io/cart315/box2.html

**Comment by NPhuongHao** [comment]
Phuong Hao Nguyen

https://hybrid.concordia.ca/NG_AO/cart315-2020/PhuongHao_N_the_serpentine_witch.html

**Comment by forteller11** [comment]
Charly Yan Miller
[https://forteller11.itch.io/make-a-thing](url)

**Comment by madslads** [comment]
Maddi - So you wake up in a cabin.. - Twine game:
[https://twinery.org/2/#!/stories/00d7844e-e211-44a4-8a32-eb0fabdc736a/test/ca1524b7-3318-455f-81bd-627aa92d0841](url)

**Comment by weavingmemories** [comment]
Macey McCormick

https://weavingmemories.itch.io/im-new

**Comment by Gmangray4** [comment]
Gordon Gray
https://gmangray4.github.io/GordonGitCartSite/AvoidingMotivation/index.html

**Comment by Liu-WenYue** [comment]
Liu WenYue 
https://wenyue.itch.io/unlock

**Comment by Nomad29** [comment]
Alexandra Melançon
https://alexandramelancon.com/garden/assignment01_alexandra_melancon.html

**Comment by sorwu** [comment]
Sol Paul
https://sorwu.itch.io/thinking-head

**Comment by LastEndConductor** [comment]
https://joeske.itch.io/gambling-101

**Comment by tech-witch** [comment]
🤖 Twine prototype of the robot emotion system 🦀
https://tech-witch.github.io/cart315/

**Comment by M33-Melissa** [comment]
Melissa Lim
https://www.flickgame.org/play.html?p=a2437f59634a8cece297b77dc47d6875

**Comment by mortebouse** [comment]
Nat Torre 😎
https://mortebouse.github.io/CART315/Power%20Outage%20Simulator

**Comment by Hamrang** [comment]
Hanieh - a biopunk story
https://hanieh.itch.io/genomo-inky

**Comment by Cadere** [comment]
Eugene Fournier
https://angelicuscadere.itch.io/youaredead

**Comment by Harout77** [comment]
Harout Kullukian
https://serharout.itch.io/platprot

**Comment by HazelThexton** [comment]
https://hazelthexton.github.io/DIGITAL-GAME-PROTOTYPING/assignment1/index.html
Hazel Thexton

**Comment by tiffhc** [comment]
Tiffany - Fated Letters
https://tiffhc.itch.io/cart-315-game-prototype
