### ISSUE TITLE
Team Alex and Hao [Prototype 3]

### ISSUE THREAD

**Issue by alexMelancon** [jdespland-teaching/CART315_2020#14]
**Prototype Build**
We highly recommend this version rather than downloading our GitHub repository for the playtest!
Just open the Builds folder, then select the folder corresponding to your OS and run the executable file.

https://drive.google.com/open?id=1HJGFrjVF-w57K-nTdqfaUPJeIAQl58kR

\
**GitHub Repository**
https://github.com/alexMelancon/cart315-2020-teamproject/tree/master/prototype3

\
**Survey questions**
https://docs.google.com/forms/d/e/1FAIpQLSe3YzPURX2dNXlKK5XsbpFf8JO0iFp-DVAy4D65dLkjtgs-Ow/viewform?usp=sf_link

**Comment by M33-Melissa** [comment]
I answered the survey, but I noticed after that I didn't play it from the build directly and used unity to run it so that's why I couldn't see the instruction scene before the actual game, sorry about that! Just ignore the part I talk about it xD

**Comment by Willler** [comment]
I answered the survey. Good stuff!

**Comment by forteller11** [comment]
answered the survey, like the art :)

**Comment by HazelThexton** [comment]
Answered the survey!

**Comment by tiffhc** [comment]
I have also answered the survey! I wish you guys the best! It looks great!!!
