### ISSUE TITLE
Harout's prototype 3

### ISSUE THREAD

**Issue by Harout77** [jdespland-teaching/CART315_2020#15]
**Github Repo**

- https://github.com/Harout77/CART315_HaroutKullukian/tree/master/Prototype%203

Itchio WebGl link

- https://serharout.itch.io/geo-dasher-prototype-3

Playtesting Questions

- https://docs.google.com/document/d/1qyQbruDI3pLy9Xa858LbElm_w3LOl75DYnizwcFa38U/edit?usp=sharing

**Comment by Harout77** [comment]
1. How challenging was it to finish the levels?
2. If you had to change the geos to anything else what would it be?
3. If you could add 1 thing what would it be?
4. Would you play this game on mobile?
5. Would have you understood how to play without instructions?

**Comment by Cadere** [comment]
1. The levels are reasonnably challenging, but the controls are too sensitive. The challenge is less in avoiding the objects than in trying to move less when hitting a control.

2. Idk what "geos" are

3. The music was very nice. Being able to jump might be cool

4. Yeah seems fitting for a mobile game

5. I think so yes

**Comment by miwamiwa** [comment]
How challenging was it to finish the levels?
Pretty unforgiving, but that's appealing in itself. I got past level 1 by staying out of trouble, but I couldn't get very far into level 2. I feel like things would be easier if either the left-right motion was slower or I couldn't fall off the sides. 

If you had to change the geos to anything else what would it be?
I didn't get very far into the game I think but I liked this environment made of primitive shapes. I would just make more variations on that theme.

If you could add 1 thing what would it be?
Changes in speed during gameplay

Would you play this game on mobile?
Sure

Would have you understood how to play without instructions?
Yes the text was enough.
