### ISSUE TITLE
Team Alex and Hao [Iterative Prototype 1]

### ISSUE THREAD

**Issue by alexMelancon** [jdespland-teaching/CART315_2020#21]
**GitHub Repository**
We recommend you to playtest one of the Builds rather than opening the project in Unity or the WebGL version posted below!

https://github.com/alexMelancon/cart315-2020-iterativeproject/tree/master/prototype1

\
**Survey questions**
https://docs.google.com/forms/d/e/1FAIpQLScr_EmCBiEbUDIHA5-9tyFU-2FzYmXJcOAw6R7ubZbvcjkCNw/viewform?usp=sf_link

**Comment by NPhuongHao** [comment]
Link to WebGL Build (Play at full screen to see your score displayed): https://hybrid.concordia.ca/NG_AO/cart315-2020/webgl/index.html

**Comment by alexMelancon** [comment]
> Link to WebGL Build (Play at full screen to see your score displayed): https://hybrid.concordia.ca/NG_AO/cart315-2020/webgl/index.html

**Newly patched Builds**
Playtest by downloading the GitHub repository at the top of this thread instead.

**Comment by tiffhc** [comment]
Hi guys, 

It's a great game, I can't wait to see the next iteration with maybe more abilities for the players (such as defense from enemies, more attack power towards enemies, etc.)

Fighting to the both of you!

**Comment by Gmangray4** [comment]
Great game guys! Feedback answers submitted.

**Comment by Willler** [comment]
Nice work! I answered the survey.

**Comment by Harout77** [comment]
I really like the design and aesthetic of the game, very nice!
