### ISSUE TITLE
Team TWWT (Tiffany & WenYue) Iterative Prototype 1

### ISSUE THREAD

**Issue by Liu-WenYue** [jdespland-teaching/CART315_2020#24]
**WebGL Build (Please use Google Chrome):** 
https://wenyue.itch.io/escape-maze-ip1

**Survey Questions:**
https://forms.gle/UwDTTdAniswHgRVb8

**Repository URL:** 
https://github.com/Liu-WenYue/Cart315_TeamProject_Iterative1
https://github.com/tiffhc/Cart315_TeamProjec_Iterative1

**Comment by alexMelancon** [comment]
I answered the survey! It's great and also thematic considering that Easter's coming soon :)

**Comment by Willler** [comment]
Answered the survey. Really great atmosphere!

**Comment by madslads** [comment]
The colors are really lovely, a little bit hard to tell when character is attacking you. Overall great game!
