### ISSUE TITLE
Individual Prototype results

### ISSUE THREAD

**Issue by jdespland-teaching** [jdespland-teaching/CART315_2020#3]
example:
Name: Joachim
Most succesful prototype: Prototype 2 - the one with the jumping

**Comment by LastEndConductor** [comment]
Name : Joe
Most successful prototype : 3 - combat mechanic.

**Comment by HazelThexton** [comment]
Hazel Thexton
Prototype: Arborarchy (1)
https://github.com/HazelThexton/UnityProjects/wiki

**Comment by Nomad29** [comment]
Alexandra Melançon
Most successful prototype: 3 - gravity

**Comment by weavingmemories** [comment]
Macey McCormick
Most successful prototype: 1 - Changing Maze

**Comment by mortebouse** [comment]
Name: Nat Torre
Most successful prototype: Prototype 3 (Item combination mechanic)
https://github.com/mortebouse/CART-315-Exercise-final/wiki
https://github.com/mortebouse/CART-315-Prototype-3

**Comment by Gmangray4** [comment]
Name: Gordon Gray
Most successful prototype: Prototype 2 - AI Spawning and eating them with vacuum arm. #Luigi'sMansionStyle

**Comment by madslads** [comment]
Madison Hunt
Most successful prototype - (Jitter Bean) #3 third person camera view + rotation + jitter effect on camera

**Comment by madslads** [comment]
Madison Hunt
Most successful prototype - (Jitter Bean) #3 third person camera view + rotation + jitter effect on camera

**Comment by Willler** [comment]
William L'Eriger
Most Successful Prototype: Prototype #1 Urgent Shooting
https://github.com/Willler/CART315-Class/tree/master/Prototype_1/Prototype

**Comment by NPhuongHao** [comment]
Phuong Hao NGUYEN
Most successful prototype: Prototype 3 - The colour-based snake game
https://github.com/NPhuongHao/CART315-Prototype003

**Comment by miwamiwa** [comment]
Samuel Pare-Chouinard
prototype 3 dog-platforms
https://github.com/miwamiwa/cart315/tree/master/Prototype%203

**Comment by sorwu** [comment]
Sol Paul
Prototype 3 - FPS (destroying objects/flinging created balls)
https://github.com/sorwu/cart315-2020/blob/master/Assets/Scenes/thirdPrototype2.unity

**Comment by M33-Melissa** [comment]
Melissa Lim
Most Successful Prototype: Prototype 2 - 3D obstacles platformer with 2D side-view camera.

**Comment by tiffhc** [comment]
Tiffany Chenn

Most Successful prototype - Prototype 3 Find the cactus first before the AI does. 
https://github.com/tiffhc/Cart315-Prototype3

**Comment by Liu-WenYue** [comment]
Liu WenYue
Most successful prototype: Prototype 3 - An escape room where you can drag and drop objects

**Comment by Cadere** [comment]
Eugene N. Fournier
Most successful prototype - Prototype #1: Moon Lights
A dark environment which the player explores by creating lights in the environment.
