### ISSUE TITLE
Team TWWT (Tiffany & WenYue) Iterative Prototype 2

### ISSUE THREAD

**Issue by Liu-WenYue** [jdespland-teaching/CART315_2020#30]
**Downloadable Windows Build:**
https://tiffhc.itch.io/cart-315-escape-maze-iterative-2-windows?secret=JlUGga0uU7G3KA35tHmShXwMUCg

**Downloadable Mac Build:**
https://wenyue.itch.io/escape-maze-ip2?secret=jrbgPoXGoziqrL2IsF8zykK6LY

**Survey Questions:**
https://forms.gle/1Eg4CsUwducborFK6

**URL to our GitHub repository:**
https://github.com/Liu-WenYue/Cart315_TeamProject_IterativePrototypes

**Comment by Willler** [comment]
I answered the survey. Great work! I really dig the UI improvements from last week's iteration!

**Comment by Gmangray4** [comment]
Answered the survey too. Very interesting sound design and the maze was challenging! Great work on this one guys!
